### ISSUE TITLE
Suggestions/questions

### ISSUE THREAD

**Issue by NeatWolf** [ThomasNg2/LethalHands#1]
Hi!
I love the idea and may as well fall into vanilla LC as soon as the community notices it - so it's a can of worms ready to explode :D 
(I'm thinking about compatibility with the most common mods that are still updated - VR included :P )

In the description you mentioned:

"punches will have a 50% chance to deal shovel/sign damage"
- Do you mean, in a way that's compatible with @https://thunderstore.io/c/lethal-company/p/Ccode_lang/ConfigShovel/ or @https://thunderstore.io/c/lethal-company/p/malco/Lategame_Upgrades/ ? Does it scale accordingly, regardless from the fact you're carrying a shovel or not? If not - would be nice if it could take those into account, as it would be "upgradable" as well.
Or maybe, just call the method for inflicting damage with the shovel :P 

- May I suggest to have a look at this when deciding how a punch lands? @https://thunderstore.io/c/lethal-company/p/ButteryStancakes/MeleeFixes/

- Audio/video feedback would be great (parried punch vs hitting punch sound). Even a single puff of dirt spawning when the punch connects would be great.

- Do the rules about invulnerable enemies still apply? What about those forcedfully set by @https://thunderstore.io/c/lethal-company/p/TheFluff/EverythingCanDie/ ?

- Does the mod support full network replication, or is it client only?

- "Press 'J' (configurable)" - "we have no configuration" this seems contradictory ;)

- configuration-wise I'd advise having a "hit ratio" that is applied as a multiplier of the damage when the calculated shovel damage is > 1, and used as a hit chance when such damage is 1. There are tons of events that could cause the shovel damage to increase/decrease during a match, so I'm not sure if any caching of it is going to be possible.

My 2 cents, maybe inheriting from the shovel could address many of the above issues, as there are plenty of mods that involve a shovel hit that would make sense would apply to a punch as well (mods for bashing doors, deactivating turrets, etc.)

I'm going to be testing the mod with the crew these days, thanks for creating it!

**Comment by ThomasNg2** [comment]
Hello,

- Compatibility with other mods regarding shovel damage : I mentioned shovel damage because I figured that that would be clearer than saying it deals 1 damage, especially since the health system is different for monsters and players. As of now, a successful hit is equivalent to a vanilla shovel hit, regardless of present mods.
- Better hitreg : I mostly copied the shovel code when it came to getting the target to hit and playing sounds, but I could totally implement the fixes from that mod if it leads to better hit registration.
- Whiffs : Giving punches a probability to deal no damage was kind of a last minute addition so I didn't polish it much, but yeah some kind of feedback on that should be implemented in the future
- Modified invulnerable enemies and hitting things in general : I used the Hit method from the IHittable Interface which is used by well, all the hittable things in game. So provided these kind of mods are built on that same interface, punching should trigger their extra effects.
- Network replication : Not sure what that means exactly, but the animations, sounds and entities being damaged are synced between players yes.
- Configuration : That's just a keybind and it being able to be configured is provided by another mod (so can't really say I did anything here), what I had in mind for configuration was more along the lines of tweaking how fast you can punch, the probability to land one, etc. (working on that at the moment by the way).
- Hit ratio : I think I'm going to stick to separate hit probability and damage values for now, and if I ever start looking into mod compatibility, then I'll consider it.
- Inheriting from shovel : This probably could have eased compatibility with other mods, but since the shovel is technically a GrabbableObject I'm not sure how that would have played out when it comes to granting the player the ability to punch without interfering with the item system.

Appreciate the suggestions.
